version: '3'
services:
  db:
    image: postgres:11-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: local
      POSTGRES_DB: example_db
  app:
    build:
      context: ./app
      dockerfile: ./.docker/Dockerfile
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
    image: php:7.2-fpm-alpine
    container_name: app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: local
      DB_DATABASE: example_db
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
  composer:
    image: composer
    container_name: composer
    restart: "no"
    command: install
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    depends_on:
      - app
  srv:
    image: nginx:stable-alpine
    container_name: srv
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./srv/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - app
      - composer
  