version: '3'
services:
  db:
    image: postgres:11-alpine
    container_name: db-prod
  app:
    build:
      dockerfile: ./.docker/Dockerfile.prod
    container_name: app-prod
    volumes:
      - lnpp-volume:/var/www/html
  composer:
    container_name: composer-prod
    volumes:
      - lnpp-volume:/var/www/html
  srv:
    build:
      context: ./srv
      dockerfile: ./.docker/Dockerfile.prod
    container_name: srv-prod
    volumes:
      - lnpp-volume:/var/www/html
volumes:
  lnpp-volume: 